# **Análisis de datos con Python**
Link de colab: https://colab.research.google.com/drive/1TyJxdxDo4klOCU8erjAou0QqaOu2um8r?usp=sharing
## **Contenido**

### **Primer bloque del taller**

#### **Contenedores en Python:**
- Listas, tuplas y diccionarios.
- Acceso a elementos de los contenedores y subcontenedores.
- Métodos y Funciones.

#### **Estructura de control:**
- Operadores
- Estructura condicionales.
- Estructuras iterativas.
- Listas por comprensión

### **Funciones:**
- Funciones integradas.
- Funciones definidas por usuarios: `def` y `lambda`.
- Librerías e instalación.

### **Segundo bloque del taller**

#### **Librería Numpy:**
- Arrays.
- Vectorización.
- Manipulación básica.

#### **Librería Pandas:**
- Estructura de DataFrame y Series.
- Carga de base de datos.
- Transformación básica de datos.

#### **Visualización de datos:**
- Desde objetos iterables.
- Desde Dataframe.

### **Referencias:**



# **Contenedores en Python**
Los contenedores son estructuras de datos integradas que permiten organizar, evaluar y manipular los tipos de datos. Revisaremos, las siguiente estructuras `listas`, `tuplas` y `diccionarios`.

## **Lista**

Contiene un conjunto de valores que son guardados de forma secuencial. Es mutable, es decir, se pueden agregar, quitar o modificar elementos de este.

Las `lista` son creadas con `[]` separando sus elementos por una coma. Pueden almacenar diferentes tipos de datos.

In [2]:
#Ejemplo de listas
Lista_supermercado=['manzana','pera','pan','queso','galletas']
print(Lista_supermercado)

['manzana', 'pera', 'pan', 'queso', 'galletas']


Para `acceder a los elementos de una lista` se debe utilizar `[]`. Es importante considerar que en python los índices comienzan desde `0`.

In [3]:
#Se debe identificar la posición del dato para acceder en el caso de lista

#Lista_supermercado=['manzana','pera','pan','queso','galletas']
#                     0         1      2     3       4

print(Lista_supermercado[0])
print(Lista_supermercado[-1])

manzana
galletas


Para las `listas`, se ocupa el concepto `slice`, para obtener un subcontenedor del contenedor. Los elementos dependeran de como lo realizamos. Para realizar un slice se debe utilizar `[inicio:fin-1]`.

In [8]:
print(Lista_supermercado[0:1])
print(Lista_supermercado[1:4])

['manzana']
['pera', 'pan', 'queso']


Las principales métodos para `listas` son:

- append : Agregar elemento al final.
- pop : Retorna y elimina el objecto ubicado en el índice indicado.
- remove : Se usa cuando se conoce el nombre del elemento pero no su posición.
- reverse: Cambia dirección en que se encuetran ubicacos los elementos de una lista.
- sort : Por defecto, ordena elementos de menor a mayor.
- index: Busca un elemento dentro de una lista y entrega la posición.

In [9]:
#Ejercicios de métodos para listas:

##Considera la siguientes listas inicial:
name_pokemon=['bulbasaur','charmander','squirtle']
total_pokemon=[318,309,314]

##Agregar el pokemon 'pikachu' de la lista name_pokemon
name_pokemon=['bulbasaur','charmander','squirtle']
name_pokemon.append('pikachu')
print(name_pokemon)

##Elimina a 'charmander' utilizando su posición de la lista name_pokemon
name_pokemon=['bulbasaur','charmander','squirtle']
name_pokemon.pop(1)
print(name_pokemon)

##Elimina a 'bulbasaur' utilizando su nombre de la lista name_pokemon
name_pokemon=['bulbasaur','charmander','squirtle']
name_pokemon.remove('bulbasaur')
print(name_pokemon)

##Cambia la posición de los elementos de la lista name_pokemon
name_pokemon=['bulbasaur','charmander','squirtle']
name_pokemon.reverse()
print(name_pokemon)

##Ordena los elementos de mayor a menor de la lista total_pokemon
total_pokemon=[318,309,314]
total_pokemon.sort()
print(total_pokemon)

##Busca la posición del dato 314 de la lista total_pokemon
total_pokemon=[318,309,314]
print(total_pokemon.index(314))

['bulbasaur', 'charmander', 'squirtle', 'pikachu']
['bulbasaur', 'squirtle']
['charmander', 'squirtle']
['squirtle', 'charmander', 'bulbasaur']
[309, 314, 318]
2


Funciones importantes para `listas`.

- len : Indica tamaño de lista.
- min : Mínimo valor dentro de lista.
- max : Máximo valor dentro de lista.
- sum : Suma elementos dentro de lista.

In [12]:
#Ejercicios de métodos para listas:

##Considera la siguientes listas inicial:

name_pokemon=['bulbasaur','charmander','squirtle']
total_pokemon=[318,309,314]

##Indica el tamaño de la lista name_pokemon
name_pokemon=['bulbasaur','charmander','squirtle']
print(len(name_pokemon))

##Indica el mínimo valor de la lista total_pokemon
total_pokemon=[318,309,314]
print(min(total_pokemon))

##Indica el máximo valor de la lista total_pokemon
total_pokemon=[318,309,314]
print(max(total_pokemon))

##Suma los valores de la lista total_pokemon
total_pokemon=[318,309,314]
print(sum(total_pokemon))

3
309
318
941


## **Tupla**
Son contenedores de datos no mutables, pero tienen la ventaja de usar menos memoria y son más rápidas.

La `tupla` son creadas con `()` separando sus elementos por una coma. Pueden almacenar diferentes tipos de datos.

In [14]:
#Ejemplo de tupla
Tupla_nacimiento=(27,'noviembre',1989)
print(Tupla_nacimiento)

(27, 'noviembre', 1989)


Para acceder a los elementos de una `tupla` se debe utilizar `[]`. No olvidar que en python los índices comienzan desde 0.

In [15]:
#Ejemplo para acceder a los valores de la tupla
print(Tupla_nacimiento[0])
print(Tupla_nacimiento[-1])

27
1989


En el caso de la `tupla`, se pueden ejecutar los mismos métodos y funciones de las `lista` que no generen modificaciones. Recordar que las tuplas son contenedores no mutables.

## **Diccionario**

Los diccionarios son contenedores de datos que permiten almacenar su contenido en forma de llave `key` y valor `value`.

Son creados con `{}` y son separados por una coma cada para de `key:value`.

In [16]:
#Ejemplo de diccionario
Diccionario_pokemon={'name':'pikachu','type1':'electric','Total':320}
print(Diccionario_pokemon)

{'name': 'pikachu', 'type1': 'electric', 'Total': 320}


Para acceder a los elementos de un `diccionario` se debe utilizar [].

In [17]:
#Ejemplo para acceder a los valores del diccionario
print(Diccionario_pokemon['name'])

#Otra forma es con la función .get()
print(Diccionario_pokemon.get('type1'))

pikachu
electric


Los principales métodos utilizados en un diccionario son:
- keys : Entrega una lista con todas las keys de un diccionario.
- values: Entrega una lista con todos los valores de un diccionario.
- pop : Elimina del diccionario y retorna elemento ubicado en cierta key.

In [18]:
#Ejercicios de métodos para diccionario:

## Considera el siguiente diccionario inicial:

Diccionario_pokemon={'name':'pikachu','type1':'electric','total':320}

### Indica las key del diccionario Diccionario_pokemon
Diccionario_pokemon={'name':'pikachu','type1':'electric','total':320}
print(Diccionario_pokemon.keys())

### Indica los values del diccionario Diccionario_pokemon
Diccionario_pokemon={'name':'pikachu','type1':'electric','total':320}
print(Diccionario_pokemon.values())

### Elimina el conjunto los datos de 'total' del diccionario Diccionario_pokemon
Diccionario_pokemon={'name':'pikachu','type1':'electric','total':320}
Diccionario_pokemon.pop('total')
print(Diccionario_pokemon)


dict_keys(['name', 'type1', 'total'])
dict_values(['pikachu', 'electric', 320])
{'name': 'pikachu', 'type1': 'electric'}


# **Estructura de control**

Las estructuras de control permiten programar un conjunto de instrucciones que son ejecutadas unas tras otras, mediante bloques de código que se ejecuten si solo si se dan condiciones particulares.

## **Operadores**

Existen diferentes tipos de operador:

- Operador de asignación: nos permiten realizar una operación y almacenar su resultado en la variable inicial. Los más utilizados son `=`,`+=`, `-=`, entre otros.
- Operadores aritméticos: nos permiten realziar operaciones aritméticas. Los más utilizados son `+`,`-`,`*`,`/`.
- Operadores relacionales: nos permite saber la relación existente entre dos variables. Los más utilizados son `==`, `!=`, `>` o `<`, `>=` o `=<`.
- Operadores lógicos: nos permiten operar con valores `booleanos`, solo pueden tomar el valor de `True` o `False`. Los operadores lógicos son `and` (True and True = True), `or` (True or False = True) y `not` (not true = False).

In [19]:
#Considere los siguientes datos
a=2
b=3

##Ejemplos de operadores de asignación
x=a
x+=b
print('x+=',x)

##Ejemplo de operadores aritméticos
x=a+b
print('a*b=',x)

##Ejemplo de operadores relacionales
x= a>b
print('a>b=',x)

##Ejemplo de operadores lógicos
print(True and True)

x+= 5
a*b= 5
a>b= False
True


## **Estructura condicionales**

Los condicionales son:

- if: Representa la activación de un bloque de código que se activa si es cierta una condición.
- elif: Representa el sino, una vez se escribe el primer if.
- else: Representa el resto de los casos. Por eso no lleva ninguna condición.

Ejemplo: Requerir al usuario que ingrese un día de la semana e imprimir un mensaje si es lunes, otro mensaje diferente si es viernes, otro mensaje diferente si es sábado o domingo. Si el día ingresado no es ninguno de esos, imprimir otro mensaje.


In [21]:
# Indica el día de la semana
dia= input('ingresa el día de semana:')

if (dia == 'lunes'):
  print('Pucha, recién es lunes!!')
elif (dia=='viernes'):
  print('Yuhuuuu!!!, mañana es finde....')
elif (dia == 'sabado' or 'domingo'):
  print('Finde... Findeeeee....')
else:
  print('seguimos esperando el fin de semana')

ingresa el día de semana:domingo
Finde... Findeeeee....


## **Estructuras iterativas**

Las estructuras iterativas son:

- for: el número de iteraciones se encuentra definida anticipadamente.
- while: el número de iteraciones se encuentra definida mientas que una condición se cumpla.

Ejemplo con for: elabora un ciclo for donde imprima cada letra de la palabra Python por separado.

Ejemplo con while: elabora un ciclo while donde ingrese un entero y reste 1 hasta llegar a 0.

In [22]:
# Ejemplo con for:
for i in 'Python':
  print(i)

P
y
t
h
o
n


In [23]:
# Ejemplo con while:
x= 4
while x>=0:
  print(x)
  x-=1
else:
  print('Fin del while')

4
3
2
1
0
Fin del while


## **Listas por comprensión**

Nos permite crear listas avanzadas en una misma línea de código.

Ejemplo: Crear una lista con las letras de una palabra.

In [24]:
#Utilizando una estructura iterativa for
lista=[]
for letra in 'Python':
    lista.append(letra)
print(lista)

['P', 'y', 't', 'h', 'o', 'n']


In [25]:
#Utilizando una lista por comprensión
lista = [letra for letra in 'Python']
print(lista)

['P', 'y', 't', 'h', 'o', 'n']


# **Funciones**


## **Funciones integradas**

Python tiene una serie de funciones y tipos integrados que siempre están disponibles. Algunas de las más utilizadas son:

- abs(v) : entrega valor absoluto de un valor.
- all(x) : retorna True si todos los valores de un iterable son True.
- any(x) : retorna True si algún valor de un iterable es True.
- bool(v) : retorna True al menos que el valor ingresado sea vacío, False, None o 0.
- float(v) : transforma valor a número de punto flotante (a decimal).
- int(v) : transforma valor a número entero.
- list(x) : crea un objeto tipo lista.
- pow(b,e) : calcula (alternativa a b**e).
- print(o) : convierte a string y muestra en pantalla un objeto.
- range(i,f,s): crea una secuencia de números enteros desde i hasta f-1 con salto s.
- round(v, n) : redondea un valor a n decimales.
- str(o) : convierte un objecto a string.
- type(o) : retorna tipo de un objeto.


## **Funciones definidas por los usuarios**

Existen dos tipos de funciones:

- def: permite definir nuestras propias funciones. Una vez definida podemos reutilizarlo.
- lambda: permite definir nuestra propia función. Sin embargo, no podemos reutilizarla de forma posterior.

Las funciones lambda son simplemente una versión acortada.

Ejemplo: Función para sumar dos números.


In [26]:
#Utilizando def
def suma(a,b):
  return a+b

In [27]:
#Utilizando lambda
x= lambda a,b: a+b

## **Librerías e instalación**

Las librerías de Python son conjuntos de funciones que permiten realizar distintas funciones, ahorrando tiempo y esfuerzo al programador.

Un aspecto relevante, es que cada librería tiene un objetivo. Las librerías más utilizadas para el analisis de datos son Numpy, Pandas y Matplotlib.

Colab ya viene con librerias instaladas solo debemos utilizar el siguiente código importarlas y tener acceso.

In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Para saber que librerías tenemos instaladas podemos utilizar el comando !pip freeze.

In [ ]:
!pip freeze

Para instalar un nueva librería utilizamos el comando !pip install <librería>

In [ ]:
!pip install dash

# **Numpy**

`NumPy` (*Numerical Python*) es uno de las `librerías` más importantes y, probablemente, el más utilizado en el campo del cálculo numérico en el ecosistema de `Python`. `NumPy` extiende esta funcionalidad en el campo del cálculo numérico de la siguiente manera:

- Ofrece el objeto `ndarray`, similar a una lista de `Python` pero optimizada para el cálculo numérico. Nos referiremos a este objeto como `array` de `NumPy`, o simplemente `array`.
- Implementa funciones matemáticas que pueden trabajar directamente sobre `arrays` sin tener que implementar bucles.
- Proporciona funciones para leer/escribir datos a archivos de manera optimizada.
- Permite aplicaciones de álgebra lineal, generación de números aleatorios y transformadas de Fourier.

El núcleo de `Numpy` está implementado en C, ofreciendo *bindings* en `Python` para interactuar con él. Esto se traduce en que `NumPy` es más rápido que el equivalente en puro `Python`. Muchas otras librerías para el análisis de datos están construidas sobre `NumPy`, utilizando los `ndarrays` como la estructura de datos básica debido a su eficiencia. Para ilustrar esta propiedad vamos a calcular el tiempo necesario para llevar a cabo la misma operación en puro `Python` en comparación con `arrays` de `NumPy`.

## **El objeto ndarray**

La librería `NumPy` está basado en el objeto `ndarray`. Puedes ver este objeto como una lista de `Python` con súperpoderes. El objeto `ndarray` es multidimensional, lo que implica que nos permite representar tanto valores escalares como vectores, matrices y matrices multidimensionales (lo que llamamos tensores).

Para poder trabajar con `NumPy`, primero tenemos que importarlo. Es común importarlo con el nombre np.

In [15]:
import numpy as np

Tenemos varias maneras de crear un `array`. Una de ellas es utilizar funciones implementadas en `NumPy` para la creación de `arrays`, indicando el número de elementos en cada dimensión.

In [35]:
#Crear un vector de ceros
print(np.zeros(6))

[0. 0. 0. 0. 0. 0.]


In [36]:
#Crear una matriz de ceros
print(np.zeros((3, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


De la misma manera podemos crear `arrays` de `1`, con un valor determinado o sin inicializar con las funciones `np.one()`, `np.full()` o `np.empty()` respectivamente. Estas son algunas de las propiedades de un array.

In [39]:
a= np.ones((3, 5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
#Obtener el número de elementos en cada dimension
a.shape

(3, 5)

In [41]:
#Obtener la cantidad de elementos totales en el array
a.size

15

Otra manera muy común de inicializar `arrays` de `Numpy` es mediante `listas` de `Python`. Para ello usamos la función `np.array()`.

In [43]:
a=np.array([[0, 1, 2],[3, 4, 5]])
print(a)
print(a.shape)
print(a.size)

[[0 1 2]
 [3 4 5]]
(2, 3)
6


Por último, también podemos crear `arrays` mediante funciones secuenciales o con valores aleatorios de la siguiente manera.

In [44]:
# vector de `int` en rango
np.arange(0, 7) #entrega los valores hasta (t-1)

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
# vector de `float` en rango
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## **Modificación de estructura del array**

Es muy común cambiar la forma de un `array` para acomodarlo a ciertas operaciones.

In [46]:
# array
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
# convertir en una matriz
a2 = a.reshape(2,5)
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Para poder cambiar la forma del `array` el número de elementos tiene que encajar en el número de nuevas dimensiones.

In [ ]:
a.reshape(2,4)

## **Operaciones aritméticas**
Una de las aplicaciones en las que los `arrays` de `NumPy` brillan es en la facilidad de usar operaciones artiméticas de manera optimizada y sin tener que implementar bucles como hacemos en `Python`. Esta propiedad se conoce como vectorización, algo de lo que hablaremos en más detalle en un futuro post. Podemos usar los operadores que ya conocemos de `Python` directamente con nuestros arrays.

In [49]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])

a + b

array([19, 27, 35, 43])

In [50]:
a - b

array([ 9, 19, 29, 39])

In [51]:
a*b

array([70, 92, 96, 82])

In [52]:
a / b

array([ 2.8       ,  5.75      , 10.66666667, 20.5       ])

Podremos aplicar estas operaciones siempre que las dimensiones de los `arrays` coincidan.

## **Operaciones estadísticas**

Podemos usar `NumPy` para analizar datos usando estadística. Aprenderemos diferentes métodos para calcular propiedades estadísticas de los datos, como encontrar la media y la desviación standard. Esto servirá para entender cómo podemos usar la estadística para llegar a conclusiones acerca de los datos.

La estadística nos ayuda a entender mejor los datos. Usando estadística podremos inferir, con cierta certeza, que probabilidades de ocurrencia existen sobre algo y nos ayuda a leer las propiedades acerca de los datos.

In [53]:
#Calcular el promedio
arr= np.array([4,9.4,3,2,5,6,7,6.87])
np.mean(arr)

5.4087499999999995

In [54]:
#Redondear a un número especifico de decimales
np.round(np.mean(arr),2)

5.41

In [55]:
#Calcular la mediana
arr= np.array([4,9.4,3,2,5,6])
np.median(arr)

4.5

In [56]:
#Calcular la desviación estandar
arr= np.array([1,2,3,4,4,4,6,6,7,8,8])
np.std(arr)

2.2489667048823607

Puedes obtener más información sobre operaciones estadísticas con NumPy en el siguiente link [Link](https://numpy.org/doc/stable/reference/routines.statistics.html)

# **Pandas**

`Pandas` es una librería de `Python` especializada en el manejo y análisis de estructuras de datos. Las principales características de esta librería son:

- Define una estructuras de datos basadas en los arrays de la librería `NumPy` pero con nuevas funcionalidades.
- Permite leer y escribir fácilmente ficheros en formato CSV, Excel y bases de datos SQL.
- Permite acceder a los datos mediante índices o nombres para filas y columnas.
- Ofrece métodos para reordenar, dividir y combinar conjuntos de datos.
- Permite trabajar con series temporales.
- Realiza todas estas operaciones de manera muy eficiente.

Las dos estructuras de datos de `Pandas` son las `Series` y los `Dataframes`, donde una `Serie` posee una estructura similar al `diccionario` de `Python` (par clave-valor) y un `Dataframe` es una matriz (bidimensional) con sus correspondientes filas y columnas.

En el siguiente [Link](https://pandas.pydata.org/) puedes encontrar la documentación oficial de la librería, para apoyarte en caso de dudas o consultas, cuenta con ejemplos para apoyar el aprendizaje.

Para poder trabajar con `Pandas`, primero tenemos que importarlo. Es comun importarlo con `pd`.

In [3]:
import pandas as pd

## **Series**

Es una estructura de datos unidimensional con un conjunto de datos asociados a un índice. Se puede crear directamente desde un array o una lista. Cada dato de una serie va asociado a un índice (index).

In [8]:
#Ejemplo de crear Series con del total de habilidad de cada pokemon
pd.Series([318,309,314], index=['bulbasaur','charmander','squirtle'])

bulbasaur     318
charmander    309
squirtle      314
dtype: int64

In [10]:
#Promedio de habilidad de cada pokemon
pd.Series([318,309,314], index=['bulbasaur','charmander','squirtle']).mean()

313.6666666666667

Se puede obtener otra información de índole estadístico. Puedes encontrar más información en la documentación apretando el siguiente [Link](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mean.html#pandas.Series.mean).



## DataFrame

Es una estructura de datos tabulares bidimensional, potencialmente heterogénea y de tamaño variable, con ejes etiquetados (filas y columnas). Un marco de datos es una estructura de datos bidimensional, es decir, los datos están alineados en forma de tabla en filas y columnas. Pandas DataFrame consta de tres componentes principales: datos , filas y columnas .

In [25]:
dic_pokemon={
  'Nombre':['bulbasaur','charmander','squirtle'],
  'Type1':['grass','fire','water'],
  'Total':[318,309,314]
}

pd.DataFrame(dic_pokemon)

Nombre  Type1  Total
0   bulbasaur  grass    318
1  charmander   fire    309
2    squirtle  water    314